# Pandas

In [4]:
# Press shift-enter to execute a Jupyter notebook cell
# Import the Python Libraries used in the tutorial
import numpy as np
import scipy as sp
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Enable inline plotting
%matplotlib inline

## Pandas
The main focus of this tutorial is using the Pandas library to manipulate and analyze data.

Pandas is a python package that deals mostly with :
- **Series**  (1-D homogeneous array)
- **DataFrame** (2-D labeled heterogeneous array) 
- **MultiIndex** (for hierarchical data)
- **Xarray** (built on top of Pandas for n-D arrays)

### Pandas Series

A Pandas *Series* is a 1-dimensional labeled array containing data of the same type (integers, strings, floating point numbers, Python objects, etc. ). It is a generalized numpy array with an explicit axis called the *index*.

In [5]:
# Example of creating Pandas series :
# Order all S1 together
s1 = pd.Series([-3, -1, 1, 3, 5])
print(s1)

0   -3
1   -1
2    1
3    3
4    5
dtype: int64

We did not pass any index, so by default, it assigned the indexes ranging from 0 to len(data)-1

In [6]:
# View index values
print(s1.index)

RangeIndex(start=0, stop=5, step=1)

In [7]:
s1[:2] # First 2 elements

0   -3
1   -1
dtype: int64

In [8]:
print(s1[[2,1,0]])  # Elements out of order

2    1
1   -1
0   -3
dtype: int64

In [9]:
type(s1)

pandas.core.series.Series

In [10]:
# Can place filtering conditions on series
s1[s1 > 0]

2    1
3    3
4    5
dtype: int64

In [11]:
# Creating Pandas series with index:
rng = np.random.default_rng()
s2 = pd.Series(rng.normal(size=5), index=['a', 'b', 'c', 'd', 'e'])
print(s2)

a    0.760479
b   -1.952183
c    0.591573
d    0.684134
e    0.299545
dtype: float64

In [12]:
# View index values
print(s2.index)

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [13]:
# Create a Series from dictionary
data = {'pi': 3.14159, 'e': 2.71828}  # dictionary
print(data)
s3 = pd.Series(data)
print(s3)

{'pi': 3.14159, 'e': 2.71828}
pi    3.14159
e     2.71828
dtype: float64

In [14]:
# Create a new series from a dictionary and reorder the elements
s4 = pd.Series(data, index=['e', 'pi', 'tau'])
print(s4)

e      2.71828
pi     3.14159
tau        NaN
dtype: float64

NaN (Not a Number) - is used to specify a missing value in Pandas.

In [15]:
# Series can be treated as a 1-D array and you can apply functions to them:
print("Median:", s4.median())

Median: 2.929935

In [16]:
# Methods can be used to filter series:
s4[s4 > s4.median()]

pi    3.14159
dtype: float64

### Attributes and Methods:
An attribute is a variable stored in the object, e.g., index or size with Series.
A method is a function stored in the object, e.g., head() or median() with Series.

|  Attribute/Method | Description |
|-----|-----|
| dtype | data type of values in series |
| empty | True if series is empty |
| size | number of elements |
| values | Returns values as ndarray |
| head() | First n elements |
| tail() | Last n elements |

Execute *dir(s1)* to see all attributes and methods. 

I recommend using online documentation as well. This will be in a much easier format to read and come with examples.

In [17]:
# For more information on a particular method or attribute use the help() function
help(s4.head())

Help on Series in module pandas.core.series object:

class Series(pandas.core.base.IndexOpsMixin, pandas.core.generic.NDFrame)
 |  Series(data=None, index=None, dtype: 'Dtype | None' = None, name=None, copy: 'bool' = False, fastpath: 'bool' = False)
 |
 |  One-dimensional ndarray with axis labels (including time series).
 |
 |  Labels need not be unique but must be a hashable type. The object
 |  supports both integer- and label-based indexing and provides a host of
 |  methods for performing operations involving the index. Statistical
 |  methods from ndarray have been overridden to automatically exclude
 |  missing data (currently represented as NaN).
 |
 |  Operations between Series (+, -, /, *, **) align values based on their
 |  associated index values-- they need not be the same length. The result
 |  index will be the sorted union of the two indexes.
 |
 |  Parameters
 |  ----------
 |  data : array-like, Iterable, dict, or scalar value
 |      Contains data stored in Series. If data is a dict, argument order is
 |      maintained.
 |  index : array-like or Index (1d)
 |      Values must be hashable and have the same length as `data`.
 |      Non-unique index values are allowed. Will default to
 |      RangeIndex (0, 1, 2, ..., n) if not provided. If data is dict-like
 |      and index is None, then the keys in the data are used as the index. If the
 |      index is not None, the resulting Series is reindexed with the index values.
 |  dtype : str, numpy.dtype, or ExtensionDtype, optional
 |      Data type for the output Series. If not specified, this will be
 |      inferred from `data`.
 |      See the :ref:`user guide <basics.dtypes>` for more usages.
 |  name : str, optional
 |      The name to give to the Series.
 |  copy : bool, default False
 |      Copy input data. Only affects Series or 1d ndarray input. See examples.
 |
 |  Examples
 |  --------
 |  Constructing Series from a dictionary with an Index specified
 |
 |  >>> d = {'a': 1, 'b': 2, 'c': 3}
 |  >>> ser = pd.Series(data=d, index=['a', 'b', 'c'])
 |  >>> ser
 |  a   1
 |  b   2
 |  c   3
 |  dtype: int64
 |
 |  The keys of the dictionary match with the Index values, hence the Index
 |  values have no effect.
 |
 |  >>> d = {'a': 1, 'b': 2, 'c': 3}
 |  >>> ser = pd.Series(data=d, index=['x', 'y', 'z'])
 |  >>> ser
 |  x   NaN
 |  y   NaN
 |  z   NaN
 |  dtype: float64
 |
 |  Note that the Index is first build with the keys from the dictionary.
 |  After this the Series is reindexed with the given Index values, hence we
 |  get all NaN as a result.
 |
 |  Constructing Series from a list with `copy=False`.
 |
 |  >>> r = [1, 2]
 |  >>> ser = pd.Series(r, copy=False)
 |  >>> ser.iloc[0] = 999
 |  >>> r
 |  [1, 2]
 |  >>> ser
 |  0    999
 |  1      2
 |  dtype: int64
 |
 |  Due to input data type the Series has a `copy` of
 |  the original data even though `copy=False`, so
 |  the data is unchanged.
 |
 |  Constructing Series from a 1d ndarray with `copy=False`.
 |
 |  >>> r = np.array([1, 2])
 |  >>> ser = pd.Series(r, copy=False)
 |  >>> ser.iloc[0] = 999
 |  >>> r
 |  array([999,   2])
 |  >>> ser
 |  0    999
 |  1      2
 |  dtype: int64
 |
 |  Due to input data type the Series has a `view` on
 |  the original data, so
 |  the data is changed as well.
 |
 |  Method resolution order:
 |      Series
 |      pandas.core.base.IndexOpsMixin
 |      pandas.core.arraylike.OpsMixin
 |      pandas.core.generic.NDFrame
 |      pandas.core.base.PandasObject
 |      pandas.core.accessor.DirNamesMixin
 |      pandas.core.indexing.IndexingMixin
 |      builtins.object
 |
 |  Methods defined here:
 |
 |  __array__(self, dtype: 'NpDtype | None' = None) -> 'np.ndarray'
 |      Return the values as a NumPy array.
 |
 |      Users should not call this directly. Rather, it is invoked by
 |      :func:`numpy.array` and :func:`numpy.asarray`.
 |
 |      Parameters
 |      ----------
 |      dtype : str or numpy.dtype, optional
 |          The dtype to use for the resulting NumPy array. By default,
 |          the dtype is inferred from the data.
 |
 |      Returns
 |      -------
 |      numpy.ndarray
 |          The values in the series converted to a :class:`numpy.ndarray`
 |          with the specified `dtype`.
 |
 |      See Also
 |      --------
 |      array : Create a new array from data.
 |      Series.array : Zero-copy view to the array backing the Series.
 |      Series.to_numpy : Series method for similar behavior.
 |
 |      Examples
 |      --------
 |      >>> ser = pd.Series([1, 2, 3])
 |      >>> np.asarray(ser)
 |      array([1, 2, 3])
 |
 |      For timezone-aware data, the timezones may be retained with
 |      ``dtype='object'``
 |
 |      >>> tzser = pd.Series(pd.date_range('2000', periods=2, tz="CET"))
 |      >>> np.asarray(tzser, dtype="object")
 |      array([Timestamp('2000-01-01 00:00:00+0100', tz='CET'),
 |             Timestamp('2000-01-02 00:00:00+0100', tz='CET')],
 |            dtype=object)
 |
 |      Or the values may be localized to UTC and the tzinfo discarded with
 |      ``dtype='datetime64[ns]'``
 |
 |      >>> np.asarray(tzser, dtype="datetime64[ns]")  # doctest: +ELLIPSIS
 |      array(['1999-12-31T23:00:00.000000000', ...],
 |            dtype='datetime64[ns]')
 |
 |  __float__(self)
 |
 |  __getitem__(self, key)
 |
 |  __init__(self, data=None, index=None, dtype: 'Dtype | None' = None, name=None, copy: 'bool' = False, fastpath: 'bool' = False)
 |      Initialize self.  See help(type(self)) for accurate signature.
 |
 |  __int__(self)
 |
 |  __len__(self) -> 'int'
 |      Return the length of the Series.
 |
 |  __long__ = __int__(self)
 |
 |  __matmul__(self, other)
 |      Matrix multiplication using binary `@` operator in Python>=3.5.
 |
 |  __repr__(self) -> 'str'
 |      Return a string representation for a particular Series.
 |
 |  __rmatmul__(self, other)
 |      Matrix multiplication using binary `@` operator in Python>=3.5.
 |
 |  __setitem__(self, key, value) -> 'None'
 |
 |  add(self, other, level=None, fill_value=None, axis=0)
 |      Return Addition of series and other, element-wise (binary operator `add`).
 |
 |      Equivalent to ``series + other``, but with support to substitute a fill_value for
 |      missing data in either one of the inputs.
 |
 |      Parameters
 |      ----------
 |      other : Series or scalar value
 |      fill_value : None or float value, default None (NaN)
 |          Fill existing missing (NaN) values, and any new element needed for
 |          successful Series alignment, with this value before computation.
 |          If data in both corresponding Series locations is missing
 |          the result of filling (at that location) will be missing.
 |      level : int or name
 |          Broadcast across a level, matching Index values on the
 |          passed MultiIndex level.
 |
 |      Returns
 |      -------
 |      Series
 |          The result of the operation.
 |
 |      See Also
 |      --------
 |      Series.radd : Reverse of the Addition operator, see
 |          `Python documentation
 |          <https://docs.python.org/3/reference/datamodel.html#emulating-numeric-types>`_
 |          for more details.
 |
 |      Examples
 |      --------
 |      >>> a = pd.Series([1, 1, 1, np.nan], index=['a', 'b', 'c', 'd'])
 |      >>> a
 |      a    1.0
 |      b    1.0
 |      c    1.0
 |      d    NaN
 |      dtype: float64
 |      >>> b = pd.Series([1, np.nan, 1, np.nan], index=['a', 'b', 'd', 'e'])
 |      >>> b
 |      a    1.0
 |      b    NaN
 |      d    1.0
 |      e    NaN
 |      dtype: float64
 |      >>> a.add(b, fill_value=0)
 |      a    2.0
 |      b    1.0
 |      c    1.0
 |      d    1.0
 |      e    NaN
 |      dtype: float64
 |
 |  agg = aggregate(self, func=None, axis=0, *args, **kwargs)
 |
 |  aggregate(self, func=None, axis=0, *args, **kwargs)
 |      Aggregate using one or more operations over the specified axis.
 |
 |      Parameters
 |      ----------
 |      func : function, str, list or dict
 |          Function to use for aggregating the data. If a function, must either
 |          work when passed a Series or when passed to Series.apply.
 |
 |          Accepted combinations are:
 |
 |          - function
 |          - string function name
 |          - list of functions and/or function names, e.g. ``[np.sum, 'mean']``
 |          - dict of axis labels -> functions, function names or list of such.
 |      axis : {0 or 'index'}
 |              Parameter needed for compatibility with DataFrame.
 |      *args
 |          Positional arguments to pass to `func`.
 |      **kwargs
 |          Keyword arguments to pass to `func`.
 |
 |      Returns
 |      -------
 |      scalar, Series or DataFrame
 |
 |          The return can be:
 |
 |          * scalar : when Series.agg is called with single function
 |          * Series : when DataFrame.agg is called with a single function
 |          * DataFrame : when DataFrame.agg is called with several functions
 |
 |          Return scalar, Series or DataFrame.
 |
 |      See Also
 |      --------
 |      Series.apply : Invoke function on a Series.
 |      Series.transform : Transform function producing a Series with like indexes.
 |
 |      Notes
 |      -----
 |      `agg` is an alias for `aggregate`. Use the alias.
 |
 |      Functions that mutate the passed object can produce unexpected
 |      behavior or errors and are not supported. See :ref:`gotchas.udf-mutation`
 |      for more details.
 |
 |      A passed user-defined-function will be passed a Series for evaluation.
 |
 |      Examples
 |      --------
 |      >>> s = pd.Series([1, 2, 3, 4])
 |      >>> s
 |      0    1
 |      1    2
 |      2    3
 |      3    4
 |      dtype: int64
 |
 |      >>> s.agg('min')
 |      1
 |
 |      >>> s.agg(['min', 'max'])
 |      min   1
 |      max   4
 |      dtype: int64
 |
 |  align(self, other, join='outer', axis=None, level=None, copy=True, fill_value=None, method=None, limit=None, fill_axis=0, broadcast_axis=None)
 |      Align two objects on their axes with the specified join method.
 |
 |      Join method is specified for each axis Index.
 |
 |      Parameters
 |      ----------
 |      other : DataFrame or Series
 |      join : {'outer', 'inner', 'left', 'right'}, default 'outer'
 |      axis : allowed axis of the other object, default None
 |          Align on index (0), columns (1), or both (None).
 |      level : int or level name, default None
 |          Broadcast across a level, matching Index values on the
 |          passed MultiIndex level.
 |      copy : bool, default True
 |          Always returns new objects. If copy=False and no reindexing is
 |          required then original objects are returned.
 |      fill_value : scalar, default np.NaN
 |          Value to use for missing values. Defaults to NaN, but can be any
 |          "compatible" value.
 |      method : {'backfill', 'bfill', 'pad', 'ffill', None}, default None
 |          Method to use for filling holes in reindexed Series:
 |
 |          - pad / ffill: propagate last valid observation forward to next valid.
 |          - backfill / bfill: use NEXT valid observation to fill gap.
 |
 |      limit : int, default None
 |          If method is specified, this is the maximum number of consecutive
 |          NaN values to forward/backward fill. In other words, if there is
 |          a gap with more than this number of consecutive NaNs, it will only
 |          be partially filled. If method is not specified, this is the
 |          maximum number of entries along the entire axis where NaNs will be
 |          filled. Must be greater than 0 if not None.
 |      fill_axis : {0 or 'index'}, default 0
 |          Filling axis, method and limit.
 |      broadcast_axis : {0 or 'index'}, default None
 |          Broadcast values along this axis, if aligning two objects of
 |          different dimensions.
 |
 |      Returns
 |      -------
 |      (left, right) : (Series, type of other)
 |          Aligned objects.
 |
 |  all(self, axis=0, bool_only=None, skipna=True, level=None, **kwargs)
 |      Return whether all elements are True, potentially over an axis.
 |
 |      Returns True unless there at least one element within a series or
 |      along a Dataframe axis that is False or equivalent (e.g. zero or
 |      empty).
 |
 |      Parameters
 |      ----------
 |      axis : {0 or 'index', 1 or 'columns', None}, default 0
 |          Indicate which axis or axes should be reduced.
 |
 |          * 0 / 'index' : reduce the index, return a Series whose index is the
 |            original column labels.
 |          * 1 / 'columns' : reduce the columns, return a Series whose index is the
 |            original index.
 |          * None : reduce all axes, return a scalar.
 |
 |      bool_only : bool, default None
 |          Include only boolean columns. If None, will attempt to use everything,
 |          then use only boolean data. Not implemented for Series.
 |      skipna : bool, default True
 |          Exclude NA/null values. If the entire row/column is NA and skipna is
 |          True, then the result will be True, as for an empty row/column.
 |          If skipna is False, then NA are treated as True, because these are not
 |          equal to zero.
 |      level : int or level name, default None
 |          If the axis is a MultiIndex (hierarchical), count along a
 |          particular level, collapsing into a scalar.
 |      **kwargs : any, default None
 |          Additional keywords have no effect but might be accepted for
 |          compatibility with NumPy.
 |
 |      Returns
 |      -------
 |      scalar or Series
 |          If level is specified, then, Series is returned; otherwise, scalar
 |          is returned.
 |
 |      See Also
 |      --------
 |      Series.all : Return True if all elements are True.
 |      DataFrame.any : Return True if one (or more) elements are True.
 |
 |      Examples
 |      --------
 |      **Series**
 |
 |      >>> pd.Series([True, True]).all()
 |      True
 |      >>> pd.Series([True, False]).all()
 |      False
 |      >>> pd.Series([], dtype="float64").all()
 |      True
 |      >>> pd.Series([np.nan]).all()
 |      True
 |      >>> pd.Series([np.nan]).all(skipna=False)
 |      True
 |
 |      **DataFrames**
 |
 |      Create a dataframe from a dictionary.
 |
 |      >>> df = pd.DataFrame({'col1': [True, True], 'col2': [True, False]})
 |      >>> df
 |         col1   col2
 |      0  True   True
 |      1  True  False
 |
 |      Default behaviour checks if column-wise values all return True.
 |
 |      >>> df.all()
 |      col1     True
 |      col2    False
 |      dtype: bool
 |
 |      Specify ``axis='columns'`` to check if row-wise values all return True.
 |
 |      >>> df.all(axis='columns')
 |      0     True
 |      1    False
 |      dtype: bool
 |
 |      Or ``axis=None`` for whether every value is True.
 |
 |      >>> df.all(axis=None)
 |      False
 |
 |  any(self, axis=0, bool_only=None, skipna=True, level=None, **kwargs)
 |      Return whether any element is True, potentially over an axis.
 |
 |      Returns False unless there is at least one element within a series or
 |      along a Dataframe axis that is True or equivalent (e.g. non-zero or
 |      non-empty).
 |
 |      Parameters
 |      ----------
 |      axis : {0 or 'index', 1 or 'columns', None}, default 0
 |          Indicate which axis or axes should be reduced.
 |
 |          * 0 / 'index' : reduce the index, return a Series whose index is the
 |            original column labels.
 |          * 1 / 'columns' : reduce the columns, return a Series whose index is the
 |            original index.
 |          * None : reduce all axes, return a scalar.
 |
 |      bool_only : bool, default None
 |          Include only boolean columns. If None, will attempt to use everything,
 |          then use only boolean data. Not implemented for Series.
 |      skipna : bool, default True
 |          Exclude NA/null values. If the entire row/column is NA and skipna is
 |          True, then the result will be False, as for an empty row/column.
 |          If skipna is False, then NA are treated as True, because these are not
 |          equal to zero.
 |      level : int or level name, default None
 |          If the axis is a MultiIndex (hierarchical), count along a
 |          particular level, collapsing into a scalar.
 |      **kwargs : any, default None
 |          Additional keywords have no effect but might be accepted for
 |          compatibility with NumPy.
 |
 |      Returns
 |      -------
 |      scalar or Series
 |          If level is specified, then, Series is returned; otherwise, scalar
 |          is returned.
 |
 |      See Also
 |      --------
 |      numpy.any : Numpy version of this method.
 |      Series.any : Return whether any element is True.
 |      Series.all : Return whether all elements are True.
 |      DataFrame.any : Return whether any element is True over requested axis.
 |      DataFrame.all : Return whether all elements are True over requested axis.
 |
 |      Examples
 |      --------
 |      **Series**
 |
 |      For Series input, the output is a scalar indicating whether any element
 |      is True.
 |
 |      >>> pd.Series([False, False]).any()
 |      False
 |      >>> pd.Series([True, False]).any()
 |      True
 |      >>> pd.Series([], dtype="float64").any()
 |      False
 |      >>> pd.Series([np.nan]).any()
 |      False
 |      >>> pd.Series([np.nan]).any(skipna=False)
 |      True
 |
 |      **DataFrame**
 |
 |      Whether each column contains at least one True element (the default).
 |
 |      >>> df = pd.DataFrame({"A": [1, 2], "B": [0, 2], "C": [0, 0]})
 |      >>> df
 |         A  B  C
 |      0  1  0  0
 |      1  2  2  0
 |
 |      >>> df.any()
 |      A     True
 |      B     True
 |      C    False
 |      dtype: bool
 |
 |      Aggregating over the columns.
 |
 |      >>> df = pd.DataFrame({"A": [True, False], "B": [1, 2]})
 |      >>> df
 |             A  B
 |      0   True  1
 |      1  False  2
 |
 |      >>> df.any(axis='columns')
 |      0    True
 |      1    True
 |      dtype: bool
 |
 |      >>> df = pd.DataFrame({"A": [True, False], "B": [1, 0]})
 |      >>> df
 |             A  B
 |      0   True  1
 |      1  False  0
 |
 |      >>> df.any(axis='columns')
 |      0    True
 |      1    False
 |      dtype: bool
 |
 |      Aggregating over the entire DataFrame with ``axis=None``.
 |
 |      >>> df.any(axis=None)
 |      True
 |
 |      `any` for an empty DataFrame is an empty Series.
 |
 |      >>> pd.DataFrame([]).any()
 |      Series([], dtype: bool)
 |
 |  append(self, to_append, ignore_index: 'bool' = False, verify_integrity: 'bool' = False)
 |      Concatenate two or more Series.
 |
 |      Parameters
 |      ----------
 |      to_append : Series or list/tuple of Series
 |          Series to append with self.
 |      ignore_index : bool, default False
 |          If True, the resulting axis will be labeled 0, 1, …, n - 1.
 |      verify_integrity : bool, default False
 |          If True, raise Exception on creating index with duplicates.
 |
 |      Returns
 |      -------
 |      Series
 |          Concatenated Series.
 |
 |      See Also
 |      --------
 |      concat : General function to concatenate DataFrame or Series objects.
 |
 |      Notes
 |      -----
 |      Iteratively appending to a Series can be more computationally intensive
 |      than a single concatenate. A better solution is to append values to a
 |      list and then concatenate the list with the original Series all at
 |      once.
 |
 |      Examples
 |      --------
 |      >>> s1 = pd.Series([1, 2, 3])
 |      >>> s2 = pd.Series([4, 5, 6])
 |      >>> s3 = pd.Series([4, 5, 6], index=[3, 4, 5])
 |      >>> s1.append(s2)
 |      0    1
 |      1    2
 |      2    3
 |      0    4
 |      1    5
 |      2    6
 |      dtype: int64
 |
 |      >>> s1.append(s3)
 |      0    1

In [18]:
help(s4.index)

Help on Index in module pandas.core.indexes.base object:

class Index(pandas.core.base.IndexOpsMixin, pandas.core.base.PandasObject)
 |  Index(data=None, dtype=None, copy=False, name=None, tupleize_cols=True, **kwargs) -> 'Index'
 |
 |  Immutable sequence used for indexing and alignment. The basic object
 |  storing axis labels for all pandas objects.
 |
 |  Parameters
 |  ----------
 |  data : array-like (1-dimensional)
 |  dtype : NumPy dtype (default: object)
 |      If dtype is None, we find the dtype that best fits the data.
 |      If an actual dtype is provided, we coerce to that dtype if it's safe.
 |      Otherwise, an error will be raised.
 |  copy : bool
 |      Make a copy of input ndarray.
 |  name : object
 |      Name to be stored in the index.
 |  tupleize_cols : bool (default: True)
 |      When True, attempt to create a MultiIndex if possible.
 |
 |  See Also
 |  --------
 |  RangeIndex : Index implementing a monotonic integer range.
 |  CategoricalIndex : Index of :class:`Categorical` s.
 |  MultiIndex : A multi-level, or hierarchical Index.
 |  IntervalIndex : An Index of :class:`Interval` s.
 |  DatetimeIndex : Index of datetime64 data.
 |  TimedeltaIndex : Index of timedelta64 data.
 |  PeriodIndex : Index of Period data.
 |  Int64Index : A special case of :class:`Index` with purely integer labels.
 |  UInt64Index : A special case of :class:`Index` with purely unsigned integer labels.
 |  Float64Index : A special case of :class:`Index` with purely float labels.
 |
 |  Notes
 |  -----
 |  An Index instance can **only** contain hashable objects
 |
 |  Examples
 |  --------
 |  >>> pd.Index([1, 2, 3])
 |  Int64Index([1, 2, 3], dtype='int64')
 |
 |  >>> pd.Index(list('abc'))
 |  Index(['a', 'b', 'c'], dtype='object')
 |
 |  Method resolution order:
 |      Index
 |      pandas.core.base.IndexOpsMixin
 |      pandas.core.arraylike.OpsMixin
 |      pandas.core.base.PandasObject
 |      pandas.core.accessor.DirNamesMixin
 |      builtins.object
 |
 |  Methods defined here:
 |
 |  __abs__(self)
 |
 |  __and__(self, other)
 |
 |  __array__(self, dtype=None) -> 'np.ndarray'
 |      The array interface, return my values.
 |
 |  __array_wrap__(self, result, context=None)
 |      Gets called after a ufunc and other functions.
 |
 |  __bool__ = __nonzero__(self)
 |
 |  __contains__(self, key: 'Any') -> 'bool'
 |      Return a boolean indicating whether the provided key is in the index.
 |
 |      Parameters
 |      ----------
 |      key : label
 |          The key to check if it is present in the index.
 |
 |      Returns
 |      -------
 |      bool
 |          Whether the key search is in the index.
 |
 |      Raises
 |      ------
 |      TypeError
 |          If the key is not hashable.
 |
 |      See Also
 |      --------
 |      Index.isin : Returns an ndarray of boolean dtype indicating whether the
 |          list-like key is in the index.
 |
 |      Examples
 |      --------
 |      >>> idx = pd.Index([1, 2, 3, 4])
 |      >>> idx
 |      Int64Index([1, 2, 3, 4], dtype='int64')
 |
 |      >>> 2 in idx
 |      True
 |      >>> 6 in idx
 |      False
 |
 |  __copy__(self: '_IndexT', **kwargs) -> '_IndexT'
 |
 |  __deepcopy__(self: '_IndexT', memo=None) -> '_IndexT'
 |      Parameters
 |      ----------
 |      memo, default None
 |          Standard signature. Unused
 |
 |  __getitem__(self, key)
 |      Override numpy.ndarray's __getitem__ method to work as desired.
 |
 |      This function adds lists and Series as valid boolean indexers
 |      (ndarrays only supports ndarray with dtype=bool).
 |
 |      If resulting ndim != 1, plain ndarray is returned instead of
 |      corresponding `Index` subclass.
 |
 |  __iadd__(self, other)
 |
 |  __inv__(self)
 |
 |  __len__(self) -> 'int'
 |      Return the length of the Index.
 |
 |  __neg__(self)
 |
 |  __nonzero__(self)
 |
 |  __or__(self, other)
 |
 |  __pos__(self)
 |
 |  __reduce__(self)
 |      Helper for pickle.
 |
 |  __repr__(self) -> 'str_t'
 |      Return a string representation for this object.
 |
 |  __setitem__(self, key, value)
 |
 |  __xor__(self, other)
 |
 |  all(self, *args, **kwargs)
 |      Return whether all elements are Truthy.
 |
 |      Parameters
 |      ----------
 |      *args
 |          Required for compatibility with numpy.
 |      **kwargs
 |          Required for compatibility with numpy.
 |
 |      Returns
 |      -------
 |      all : bool or array-like (if axis is specified)
 |          A single element array-like may be converted to bool.
 |
 |      See Also
 |      --------
 |      Index.any : Return whether any element in an Index is True.
 |      Series.any : Return whether any element in a Series is True.
 |      Series.all : Return whether all elements in a Series are True.
 |
 |      Notes
 |      -----
 |      Not a Number (NaN), positive infinity and negative infinity
 |      evaluate to True because these are not equal to zero.
 |
 |      Examples
 |      --------
 |      **all**
 |
 |      True, because nonzero integers are considered True.
 |
 |      >>> pd.Index([1, 2, 3]).all()
 |      True
 |
 |      False, because ``0`` is considered False.
 |
 |      >>> pd.Index([0, 1, 2]).all()
 |      False
 |
 |      **any**
 |
 |      True, because ``1`` is considered True.
 |
 |      >>> pd.Index([0, 0, 1]).any()
 |      True
 |
 |      False, because ``0`` is considered False.
 |
 |      >>> pd.Index([0, 0, 0]).any()
 |      False
 |
 |  any(self, *args, **kwargs)
 |      Return whether any element is Truthy.
 |
 |      Parameters
 |      ----------
 |      *args
 |          Required for compatibility with numpy.
 |      **kwargs
 |          Required for compatibility with numpy.
 |
 |      Returns
 |      -------
 |      any : bool or array-like (if axis is specified)
 |          A single element array-like may be converted to bool.
 |
 |      See Also
 |      --------
 |      Index.all : Return whether all elements are True.
 |      Series.all : Return whether all elements are True.
 |
 |      Notes
 |      -----
 |      Not a Number (NaN), positive infinity and negative infinity
 |      evaluate to True because these are not equal to zero.
 |
 |      Examples
 |      --------
 |      >>> index = pd.Index([0, 1, 2])
 |      >>> index.any()
 |      True
 |
 |      >>> index = pd.Index([0, 0, 0])
 |      >>> index.any()
 |      False
 |
 |  append(self, other: 'Index | Sequence[Index]') -> 'Index'
 |      Append a collection of Index options together.
 |
 |      Parameters
 |      ----------
 |      other : Index or list/tuple of indices
 |
 |      Returns
 |      -------
 |      Index
 |
 |  argsort(self, *args, **kwargs) -> 'np.ndarray'
 |      Return the integer indices that would sort the index.
 |
 |      Parameters
 |      ----------
 |      *args
 |          Passed to `numpy.ndarray.argsort`.
 |      **kwargs
 |          Passed to `numpy.ndarray.argsort`.
 |
 |      Returns
 |      -------
 |      np.ndarray[np.intp]
 |          Integer indices that would sort the index if used as
 |          an indexer.
 |
 |      See Also
 |      --------
 |      numpy.argsort : Similar method for NumPy arrays.
 |      Index.sort_values : Return sorted copy of Index.
 |
 |      Examples
 |      --------
 |      >>> idx = pd.Index(['b', 'a', 'd', 'c'])
 |      >>> idx
 |      Index(['b', 'a', 'd', 'c'], dtype='object')
 |
 |      >>> order = idx.argsort()
 |      >>> order
 |      array([1, 0, 3, 2])
 |
 |      >>> idx[order]
 |      Index(['a', 'b', 'c', 'd'], dtype='object')
 |
 |  asof(self, label)
 |      Return the label from the index, or, if not present, the previous one.
 |
 |      Assuming that the index is sorted, return the passed index label if it
 |      is in the index, or return the previous index label if the passed one
 |      is not in the index.
 |
 |      Parameters
 |      ----------
 |      label : object
 |          The label up to which the method returns the latest index label.
 |
 |      Returns
 |      -------
 |      object
 |          The passed label if it is in the index. The previous label if the
 |          passed label is not in the sorted index or `NaN` if there is no
 |          such label.
 |
 |      See Also
 |      --------
 |      Series.asof : Return the latest value in a Series up to the
 |          passed index.
 |      merge_asof : Perform an asof merge (similar to left join but it
 |          matches on nearest key rather than equal key).
 |      Index.get_loc : An `asof` is a thin wrapper around `get_loc`
 |          with method='pad'.
 |
 |      Examples
 |      --------
 |      `Index.asof` returns the latest index label up to the passed label.
 |
 |      >>> idx = pd.Index(['2013-12-31', '2014-01-02', '2014-01-03'])
 |      >>> idx.asof('2014-01-01')
 |      '2013-12-31'
 |
 |      If the label is in the index, the method returns the passed label.
 |
 |      >>> idx.asof('2014-01-02')
 |      '2014-01-02'
 |
 |      If all of the labels in the index are later than the passed label,
 |      NaN is returned.
 |
 |      >>> idx.asof('1999-01-02')
 |      nan
 |
 |      If the index is not sorted, an error is raised.
 |
 |      >>> idx_not_sorted = pd.Index(['2013-12-31', '2015-01-02',
 |      ...                            '2014-01-03'])
 |      >>> idx_not_sorted.asof('2013-12-31')
 |      Traceback (most recent call last):
 |      ValueError: index must be monotonic increasing or decreasing
 |
 |  asof_locs(self, where: 'Index', mask: 'np.ndarray') -> 'np.ndarray'
 |      Return the locations (indices) of labels in the index.
 |
 |      As in the `asof` function, if the label (a particular entry in
 |      `where`) is not in the index, the latest index label up to the
 |      passed label is chosen and its index returned.
 |
 |      If all of the labels in the index are later than a label in `where`,
 |      -1 is returned.
 |
 |      `mask` is used to ignore NA values in the index during calculation.
 |
 |      Parameters
 |      ----------
 |      where : Index
 |          An Index consisting of an array of timestamps.
 |      mask : np.ndarray[bool]
 |          Array of booleans denoting where values in the original
 |          data are not NA.
 |
 |      Returns
 |      -------
 |      np.ndarray[np.intp]
 |          An array of locations (indices) of the labels from the Index
 |          which correspond to the return values of the `asof` function
 |          for every element in `where`.
 |
 |  astype(self, dtype, copy=True)
 |      Create an Index with values cast to dtypes.
 |
 |      The class of a new Index is determined by dtype. When conversion is
 |      impossible, a TypeError exception is raised.
 |
 |      Parameters
 |      ----------
 |      dtype : numpy dtype or pandas type
 |          Note that any signed integer `dtype` is treated as ``'int64'``,
 |          and any unsigned integer `dtype` is treated as ``'uint64'``,
 |          regardless of the size.
 |      copy : bool, default True
 |          By default, astype always returns a newly allocated object.
 |          If copy is set to False and internal requirements on dtype are
 |          satisfied, the original data is used to create a new Index
 |          or the original Index is returned.
 |
 |      Returns
 |      -------
 |      Index
 |          Index with values cast to specified dtype.
 |
 |  copy(self: '_IndexT', name: 'Hashable | None' = None, deep: 'bool' = False, dtype: 'Dtype | None' = None, names: 'Sequence[Hashable] | None' = None) -> '_IndexT'
 |      Make a copy of this object.
 |
 |      Name and dtype sets those attributes on the new object.
 |
 |      Parameters
 |      ----------
 |      name : Label, optional
 |          Set name for new object.
 |      deep : bool, default False
 |      dtype : numpy dtype or pandas type, optional
 |          Set dtype for new object.
 |
 |          .. deprecated:: 1.2.0
 |              use ``astype`` method instead.
 |      names : list-like, optional
 |          Kept for compatibility with MultiIndex. Should not be used.
 |
 |      Returns
 |      -------
 |      Index
 |          Index refer to new object which is a copy of this object.
 |
 |      Notes
 |      -----
 |      In most cases, there should be no functional difference from using
 |      ``deep``, but if ``deep`` is passed it will attempt to deepcopy.
 |
 |  delete(self: '_IndexT', loc) -> '_IndexT'
 |      Make new Index with passed location(-s) deleted.
 |
 |      Parameters
 |      ----------
 |      loc : int or list of int
 |          Location of item(-s) which will be deleted.
 |          Use a list of locations to delete more than one value at the same time.
 |
 |      Returns
 |      -------
 |      Index
 |          Will be same type as self, except for RangeIndex.
 |
 |      See Also
 |      --------
 |      numpy.delete : Delete any rows and column from NumPy array (ndarray).
 |
 |      Examples
 |      --------
 |      >>> idx = pd.Index(['a', 'b', 'c'])
 |      >>> idx.delete(1)
 |      Index(['a', 'c'], dtype='object')
 |
 |      >>> idx = pd.Index(['a', 'b', 'c'])
 |      >>> idx.delete([0, 2])
 |      Index(['b'], dtype='object')
 |
 |  difference(self, other, sort=None)
 |      Return a new Index with elements of index not in `other`.
 |
 |      This is the set difference of two Index objects.
 |
 |      Parameters
 |      ----------
 |      other : Index or array-like
 |      sort : False or None, default None
 |          Whether to sort the resulting index. By default, the
 |          values are attempted to be sorted, but any TypeError from
 |          incomparable elements is caught by pandas.
 |
 |          * None : Attempt to sort the result, but catch any TypeErrors
 |            from comparing incomparable elements.
 |          * False : Do not sort the result.
 |
 |      Returns
 |      -------
 |      difference : Index
 |
 |      Examples
 |      --------
 |      >>> idx1 = pd.Index([2, 1, 3, 4])
 |      >>> idx2 = pd.Index([3, 4, 5, 6])
 |      >>> idx1.difference(idx2)
 |      Int64Index([1, 2], dtype='int64')
 |      >>> idx1.difference(idx2, sort=False)
 |      Int64Index([2, 1], dtype='int64')
 |
 |  drop(self, labels, errors: 'str_t' = 'raise') -> 'Index'
 |      Make new Index with passed list of labels deleted.
 |
 |      Parameters
 |      ----------
 |      labels : array-like
 |      errors : {'ignore', 'raise'}, default 'raise'
 |          If 'ignore', suppress error and existing labels are dropped.
 |
 |      Returns
 |      -------
 |      dropped : Index
 |          Will be same type as self, except for RangeIndex.
 |
 |      Raises
 |      ------
 |      KeyError
 |          If not all of the labels are found in the selected axis
 |
 |  drop_duplicates(self: '_IndexT', keep: 'str_t | bool' = 'first') -> '_IndexT'
 |      Return Index with duplicate values removed.
 |
 |      Parameters
 |      ----------
 |      keep : {'first', 'last', ``False``}, default 'first'
 |          - 'first' : Drop duplicates except for the first occurrence.
 |          - 'last' : Drop duplicates except for the last occurrence.
 |          - ``False`` : Drop all duplicates.
 |
 |      Returns
 |      -------
 |      deduplicated : Index
 |
 |      See Also
 |      --------
 |      Series.drop_duplicates : Equivalent method on Series.
 |      DataFrame.drop_duplicates : Equivalent method on DataFrame.
 |      Index.duplicated : Related method on Index, indicating duplicate
 |          Index values.
 |
 |      Examples
 |      --------
 |      Generate an pandas.Index with duplicate values.
 |
 |      >>> idx = pd.Index(['lama', 'cow', 'lama', 'beetle', 'lama', 'hippo'])
 |
 |      The `keep` parameter controls  which duplicate values are removed.
 |      The value 'first' keeps the first occurrence for each
 |      set of duplicated entries. The default value of keep is 'first'.
 |
 |      >>> idx.drop_duplicates(keep='first')
 |      Index(['lama', 'cow', 'beetle', 'hippo'], dtype='object')
 |
 |      The value 'last' keeps the last occurrence for each set of duplicated
 |      entries.
 |
 |      >>> idx.drop_duplicates(keep='last')
 |      Index(['cow', 'beetle', 'lama', 'hippo'], dtype='object')
 |
 |      The value ``False`` discards all sets of duplicated entries.
 |
 |      >>> idx.drop_duplicates(keep=False)
 |      Index(['cow', 'beetle', 'hippo'], dtype='object')
 |
 |  droplevel(self, level=0)
 |      Return index with requested level(s) removed.
 |
 |      If resulting index has only 1 level left, the result will be
 |      of Index type, not MultiIndex.
 |
 |      Parameters
 |      ----------
 |      level : int, str, or list-like, default 0
 |          If a string is given, must be the name of a level
 |          If list-like, elements must be names or indexes of levels.
 |
 |      Returns
 |      -------
 |      Index or MultiIndex
 |
 |      Examples
 |      --------
 |      >>> mi = pd.MultiIndex.from_arrays(
 |      ... [[1, 2], [3, 4], [5, 6]], names=['x', 'y', 'z'])
 |      >>> mi
 |      MultiIndex([(1, 3, 5),
 |                  (2, 4, 6)],
 |                 names=['x', 'y', 'z'])
 |
 |      >>> mi.droplevel()
 |      MultiIndex([(3, 5),
 |                  (4, 6)],
 |                 names=['y', 'z'])
 |
 |      >>> mi.droplevel(2)
 |      MultiIndex([(1, 3),
 |                  (2, 4)],
 |                 names=['x', 'y'])
 |
 |      >>> mi.droplevel('z')
 |      MultiIndex([(1, 3),
 |                  (2, 4)],
 |                 names=['x', 'y'])
 |
 |      >>> mi.droplevel(['x', 'y'])
 |      Int64Index([5, 6], dtype='int64', name='z')
 |
 |  dropna(self: '_IndexT', how: 'str_t' = 'any') -> '_IndexT'
 |      Return Index without NA/NaN values.
 |
 |      Parameters
 |      ----------
 |      how : {'any', 'all'}, default 'any'
 |          If the Index is a MultiIndex, drop the value when any or all levels
 |          are NaN.
 |
 |      Returns
 |      -------
 |      Index
 |
 |  duplicated(self, keep: "Literal[('first', 'last', False)]" = 'first') -> 'np.ndarray'
 |      Indicate duplicate index values.
 |
 |      Duplicated values are indicated as ``True`` values in the resulting
 |      array. Either all duplicates, all except the first, or all except the
 |      last occurrence of duplicates can be indicated.
 |
 |      Parameters
 |      ----------
 |      keep : {'first', 'last', False}, default 'first'
 |          The value or values in a set of duplicates to mark as missing.
 |
 |          - 'first' : Mark duplicates as ``True`` except for the first
 |            occurrence.
 |          - 'last' : Mark duplicates as ``True`` except for the last
 |            occurrence.
 |          - ``False`` : Mark all duplicates as ``True``.
 |
 |      Returns
 |      -------
 |      np.ndarray[bool]
 |
 |      See Also
 |      --------
 |      Series.duplicated : Equivalent method on pandas.Series.
 |      DataFrame.duplicated : Equivalent method on pandas.DataFrame.
 |      Index.drop_duplicates : Remove duplicate values from Index.
 |
 |      Examples
 |      --------
 |      By default, for each set of duplicated values, the first occurrence is
 |      set to False and all others to True:
 |
 |      >>> idx = pd.Index(['lama', 'cow', 'lama', 'beetle', 'lama'])
 |      >>> idx.duplicated()
 |      array([False, False,  True, False,  True])
 |
 |      which is equivalent to
 |
 |      >>> idx.duplicated(keep='first')
 |      array([False, False,  True, False,  True])
 |
 |      By using 'last', the last occurrence of each set of duplicated values
 |      is set on False and all others on True:
 |
 |      >>> idx.duplicated(keep='last')
 |      array([ True, False,  True, False, False])
 |
 |      By setting keep on ``False``, all duplicates are True:
 |
 |      >>> idx.duplicated(keep=False)
 |      array([ True, False,  True, False,  True])
 |
 |  equals(self, other: 'Any') -> 'bool'
 |      Determine if two Index object are equal.
 |
 |      The things that are being compared are:
 |

In [19]:
# You can also add a question mark to get help information
s4.head?

In [20]:
s4.index?

### Pandas DataFrames

A Pandas *DataFrame* is a 2-dimensional, size-mutable, heterogeneous tabular data structure with labeled rows and columns. You can think of it as a dictionary-like container to store Python Series objects.

In [21]:
d = pd.DataFrame({'Name': pd.Series(['Alice', 'Bob', 'Chris']), 
                  'Age': pd.Series([21, 25, 23])})
print(d)

    Name  Age
0  Alice   21
1    Bob   25
2  Chris   23

In [22]:
d2 = pd.DataFrame(np.array([['Alice','Bob','Chris'], [21, 25, 23]]).T, columns=['Name','Age'])

In [23]:
# Use the head() method to print the first 5 records in the dataframe (same as with series)
d2.head()

    Name Age
0  Alice  21
1    Bob  25
2  Chris  23

In [24]:
# Add a new column to d2:
d2['Height'] = pd.Series([5.2, 6.0, 5.6])
d2.head()

    Name Age  Height
0  Alice  21     5.2
1    Bob  25     6.0
2  Chris  23     5.6

### Reading data using Pandas
You can read CSV (comma separated values) files using Pandas. The command shown below reads a CSV file into the Pandas dataframe df.

In [25]:
# Read a csv file into Pandas Dataframe
df = pd.read_csv("Salaries.csv")

The above command has many optional arguments that you can find in the Pandas documentation online.

You can also read many other formats, for instance:
* Excel - pd.read_excel('myfile.xlsx', sheet_name='Sheet1', index_col=None, na_values=['NA'])
* Stata - pd.read_stata('myfile.dta')
* SAS - pd.read_sas('myfile.sas7bdat')
* HDF - pd.read_hdf('myfile.h5', 'df')

Before we can perform any analysis on the data we need to


*   Check if the data is correctly imported 
*   Check the types of each column
*   Determine how many missing values each column has

We can then carefully prepare the data:

*   Remove columns that are not needed in our analysis
*   Rename the columns (if necessary)
*   Possibly rearrange the columns to make it easier to work with them
*   Create new or modify existing columns (e.g., convert into different units) if necessary

In [26]:
# Display the first 10 records
df.head(10)

        rank discipline  phd  service   sex  salary
0       Prof          B   56       49  Male  186960
1       Prof          A   12        6  Male   93000
2       Prof          A   23       20  Male  110515
3       Prof          A   40       31  Male  131205
4       Prof          B   20       18  Male  104800
5       Prof          A   20       20  Male  122400
6  AssocProf          A   20       17  Male   81285
7       Prof          A   18       18  Male  126300
8       Prof          A   29       19  Male   94350
9       Prof          A   51       51  Male   57800

In [27]:
# Display structure of the data frame
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 78 entries, 0 to 77
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   rank        78 non-null     object
 1   discipline  78 non-null     object
 2   phd         78 non-null     int64
 3   service     78 non-null     int64
 4   sex         78 non-null     object
 5   salary      78 non-null     int64
dtypes: int64(3), object(3)
memory usage: 3.8+ KB

### More details on DataFrame data types

|Pandas Type | Native Python Type | Description |
|------------|--------------------|-------------|
| object | string | The most general dtype. Will be assigned to your column if column has mixed types (numbers and strings).|
| int64  | int | Numeric characters. 64 refers to the memory allocated to hold this character. |
| float64 | float | Numeric characters with decimals. If a column contains numbers and NaNs (see below), pandas will default to float64, in case your missing value has a decimal. |
| datetime64, timedelta\[ns\]| N/A (but see the datetime module in Python’s standard library) | Values meant to hold time data. Look into these for time series experiments. |


### DataFrame attributes
|df.attribute | Description |
|-------------|-------------|
| dtypes | list the types of the columns |
| columns | list the column names |
| axes | list the row labels and column names |
| ndim | number of dimensions |
| size | number of elements |
| shape | return a tuple representung the dimensionality |
| values | numpy representation of the data |

### Dataframe methods
|df.method() | Description |
|-------------|-------------|
| head(\[n\]), tail(\[n\]) | first/last n rows |
| describe() | generate descriptive statistics (for numeric columns only) |
| max(), min() | return max/min values for all numeric columns |
| mean(), median() | return mean/median values for all numeric columns |
| std() | standard deviation |
| sample(\[n\]) | returns a random sample of n elements from the data frame |
| dropna() | drop all the records with missing values |

Sometimes the column names in the input file are too long or contain special characters. In such cases we rename them to make it easier to work with these columns.

In [28]:
# Let's create a copy of this dataframe with a new column names
# If we do not want to create a new data frame, we can add inplace=True argument
df_new =df.rename(columns={'sex': 'gender', 'phd': 'yearsAfterPhD', 'service': 'yearsOfService'})
df_new.head()

   rank discipline  yearsAfterPhD  yearsOfService gender  salary
0  Prof          B             56              49   Male  186960
1  Prof          A             12               6   Male   93000
2  Prof          A             23              20   Male  110515
3  Prof          A             40              31   Male  131205
4  Prof          B             20              18   Male  104800

### DataFrame Exploration

In [29]:
# Identify the type of df_new object
type(df_new)

pandas.core.frame.DataFrame

In [30]:
# Check the data type of the column "salary"
# We access columns using the brackets, e.g., df['column_name']
df_new['salary'].dtype

dtype('int64')

In [31]:
# If the column name has no spaces, complex symbols, and is not the name of an attribute/method
# you can use the syntax df.column_name
df_new.salary.dtype

dtype('int64')

In [32]:
# List the types of all columns
df_new.dtypes

rank              object
discipline        object
yearsAfterPhD      int64
yearsOfService     int64
gender            object
salary             int64
dtype: object

In [33]:
# List the column names
df_new.columns

Index(['rank', 'discipline', 'yearsAfterPhD', 'yearsOfService', 'gender',
       'salary'],
      dtype='object')

In [34]:
# List the row labels and the column names
df_new.axes

[RangeIndex(start=0, stop=78, step=1),
 Index(['rank', 'discipline', 'yearsAfterPhD', 'yearsOfService', 'gender',
        'salary'],
       dtype='object')]

In [35]:
# Number of rows and columns
df_new.shape

(78, 6)

In [36]:
# Total number of elements in the Data Frame (78 x 6)
df_new.size

468

In [37]:
# Output some descriptive statistics for the numeric columns
df_new.describe()

       yearsAfterPhD  yearsOfService         salary
count      78.000000       78.000000      78.000000
mean       19.705128       15.051282  108023.782051
std        12.498425       12.139768   28293.661022
min         1.000000        0.000000   57800.000000
25%        10.250000        5.250000   88612.500000
50%        18.500000       14.500000  104671.000000
75%        27.750000       20.750000  126774.750000
max        56.000000       51.000000  186960.000000

In [38]:
# Remeber we can use the ? to get help about the function
df_new.describe?

In [39]:
# Create a new column using the assign method
df_new = df_new.assign(salary_k=lambda x: x.salary/1000.0)
df_new.head(10)

,rank,discipline,yearsAfterPhD,yearsOfService,gender,salary,salary_k
0,Prof,B,56,49,Male,186960,186.960
1,Prof,A,12,6,Male,93000,93.000
2,Prof,A,23,20,Male,110515,110.515
3,Prof,A,40,31,Male,131205,131.205
4,Prof,B,20,18,Male,104800,104.800
5,Prof,A,20,20,Male,122400,122.400
6,AssocProf,A,20,17,Male,81285,81.285
7,Prof,A,18,18,Male,126300,126.300
8,Prof,A,29,19,Male,94350,94.350
9,Prof,A,51,51,Male,57800,57.800

In [40]:
# Check how many unique values are in a column
# There is a rank attribute in DataFrame object so we access using df['rank']
df_new['rank'].unique()

array(['Prof', 'AssocProf', 'AsstProf'], dtype=object)

In [41]:
# Get the frequency table for a categorical or binary column
df_new['rank'].value_counts()

Prof         46
AsstProf     19
AssocProf    13
Name: rank, dtype: int64

In [42]:
# Get a proportion table
df_new['rank'].value_counts()/sum(df['rank'].value_counts())

Prof         0.589744
AsstProf     0.243590
AssocProf    0.166667
Name: rank, dtype: float64

In [43]:
# Alternatively we can use the pandas function crosstab() to calculate a frequency table
pd.crosstab(index=df_new['rank'], columns="count")

col_0      count
rank
AssocProf     13
AsstProf      19
Prof          46

In [44]:
# Two-way tables
pd.crosstab(index=df_new['rank'], columns=df_new['discipline'], margins=True)

discipline   A   B  All
rank
AssocProf    5   8   13
AsstProf     8  11   19
Prof        23  23   46
All         36  42   78

### Data slicing and grouping

In [45]:
#Extract a column by name 
df_new['gender'].head()

0    Male
1    Male
2    Male
3    Male
4    Male
Name: gender, dtype: object

In [46]:
# If the column name does not contain spaces or other special characters and does not collide with data frame methods, we can use a dot notation
df_new.gender.head()

0    Male
1    Male
2    Male
3    Male
4    Male
Name: gender, dtype: object

In [47]:
# Calculate median number of service years
df_new.yearsOfService.median()

14.5

### Grouping data

In [48]:
# Group data using rank
df_rank = df_new.groupby('rank')
df_rank.head()

,rank,discipline,yearsAfterPhD,yearsOfService,gender,salary,salary_k
0,Prof,B,56,49,Male,186960,186.960
1,Prof,A,12,6,Male,93000,93.000
2,Prof,A,23,20,Male,110515,110.515
3,Prof,A,40,31,Male,131205,131.205
4,Prof,B,20,18,Male,104800,104.800
6,AssocProf,A,20,17,Male,81285,81.285
12,AsstProf,B,1,0,Male,88000,88.000
16,AsstProf,B,8,3,Male,75044,75.044
17,AsstProf,B,4,0,Male,92000,92.000
20,AsstProf,B,4,4,Male,92000,92.000
22,AsstProf,A,4,2,Male,73000,73.000
30,AssocProf,B,9,7,Male,107008,107.008
34,AssocProf,B,12,8,Male,119800,119.800
41,AssocProf,A,13,8,Female,74830,74.830
47,AssocProf,B,11,11,Female,103613,103.613

In [49]:
# Calculate mean of all numeric columns for the grouped object
df_rank.mean()

           yearsAfterPhD  yearsOfService         salary    salary_k
rank
AssocProf      15.076923       11.307692   91786.230769   91.786231
AsstProf        5.052632        2.210526   81362.789474   81.362789
Prof           27.065217       21.413043  123624.804348  123.624804

In [50]:
# Most of the time, the "grouping" object is not stored, but is used as a step in getting a summary:
df_new.groupby('gender').mean()

        yearsAfterPhD  yearsOfService         salary    salary_k
gender
Female      16.512821       11.564103  101002.410256  101.002410
Male        22.897436       18.538462  115045.153846  115.045154

In [51]:
# Calculate the mean salary for men and women. The following produce Pandas Series (single brackets around salary)
df_new.groupby('gender')['salary'].mean()

gender
Female    101002.410256
Male      115045.153846
Name: salary, dtype: float64

In [52]:
# If we use double brackets Pandas will produce a DataFrame
df_new.groupby('gender')[['salary']].mean()

               salary
gender
Female  101002.410256
Male    115045.153846

In [53]:
# Group using 2 variables - gender and rank:
df_new.groupby(['rank','gender'], sort=True)[['salary']].mean()

                         salary
rank      gender
AssocProf Female   88512.800000
          Male    102697.666667
AsstProf  Female   78049.909091
          Male     85918.000000
Prof      Female  121967.611111
          Male    124690.142857

### Filtering

In [54]:
# Select observation with the value in the salary column > 120K
df_filter = df_new[df_new.salary > 120000]
df_filter.head()

    rank discipline  yearsAfterPhD  yearsOfService gender  salary  salary_k
0   Prof          B             56              49   Male  186960   186.960
3   Prof          A             40              31   Male  131205   131.205
5   Prof          A             20              20   Male  122400   122.400
7   Prof          A             18              18   Male  126300   126.300
10  Prof          B             39              33   Male  128250   128.250

In [55]:
df_filter.axes

[Int64Index([ 0,  3,  5,  7, 10, 11, 13, 14, 15, 19, 26, 27, 29, 31, 35, 36, 39,
             40, 44, 45, 49, 51, 58, 72, 75],
            dtype='int64'),
 Index(['rank', 'discipline', 'yearsAfterPhD', 'yearsOfService', 'gender',
        'salary', 'salary_k'],
       dtype='object')]

In [56]:
# Select data for female professors
df_w = df_new[df_new.gender == 'Female']
df_w.head()

,rank,discipline,yearsAfterPhD,yearsOfService,gender,salary,salary_k
39,Prof,B,18,18,Female,129000,129.000
40,Prof,A,39,36,Female,137000,137.000
41,AssocProf,A,13,8,Female,74830,74.830
42,AsstProf,B,4,2,Female,80225,80.225
43,AsstProf,B,5,0,Female,77000,77.000

In [57]:
# To subset one column using a condition in another columns use method "where"
df_new.salary.where(df_new.gender=='Female').dropna().head(6)

39    129000.0
40    137000.0
41     74830.0
42     80225.0
43     77000.0
44    151768.0
Name: salary, dtype: float64

### Slicing a dataframe

In [58]:
# Select column salary
salary = df_new['salary']

In [59]:
# Check data type of the result
type(salary)

pandas.core.series.Series

In [60]:
# Look at the first few elements of the output
salary.head()

0    186960
1     93000
2    110515
3    131205
4    104800
Name: salary, dtype: int64

In [61]:
# Select column salary and make the output to be a data frame
df_salary = df_new[['salary']]

In [62]:
# Check the type
type(df_salary)

pandas.core.frame.DataFrame

In [63]:
# Select a subset of rows (based on their position):
# Note 1: The location of the first row is 0
# Note 2: The last value in the range is not included
df_new[0:10]

,rank,discipline,yearsAfterPhD,yearsOfService,gender,salary,salary_k
0,Prof,B,56,49,Male,186960,186.960
1,Prof,A,12,6,Male,93000,93.000
2,Prof,A,23,20,Male,110515,110.515
3,Prof,A,40,31,Male,131205,131.205
4,Prof,B,20,18,Male,104800,104.800
5,Prof,A,20,20,Male,122400,122.400
6,AssocProf,A,20,17,Male,81285,81.285
7,Prof,A,18,18,Male,126300,126.300
8,Prof,A,29,19,Male,94350,94.350
9,Prof,A,51,51,Male,57800,57.800

In [64]:
# If we want to select both rows and columns we can use method .loc
df_new.loc[10:20, ['rank', 'gender','salary']]

        rank gender  salary
10      Prof   Male  128250
11      Prof   Male  134778
12  AsstProf   Male   88000
13      Prof   Male  162200
14      Prof   Male  153750
15      Prof   Male  150480
16  AsstProf   Male   75044
17  AsstProf   Male   92000
18      Prof   Male  107300
19      Prof   Male  150500
20  AsstProf   Male   92000

In [65]:
# Recall our filtered dataset with salaries over 120K
df_filter.head(25)

    rank discipline  yearsAfterPhD  yearsOfService  gender  salary  salary_k
0   Prof          B             56              49    Male  186960   186.960
3   Prof          A             40              31    Male  131205   131.205
5   Prof          A             20              20    Male  122400   122.400
7   Prof          A             18              18    Male  126300   126.300
10  Prof          B             39              33    Male  128250   128.250
11  Prof          B             23              23    Male  134778   134.778
13  Prof          B             35              33    Male  162200   162.200
14  Prof          B             25              19    Male  153750   153.750
15  Prof          B             17               3    Male  150480   150.480
19  Prof          A             29              27    Male  150500   150.500
26  Prof          A             38              19    Male  148750   148.750
27  Prof          A             45              43    Male  155865   155.865
29  Prof          B             21              20    Male  123683   123.683
31  Prof          B             22              21    Male  155750   155.750
35  Prof          B             28              23    Male  126933   126.933
36  Prof          B             45              45    Male  146856   146.856
39  Prof          B             18              18  Female  129000   129.000
40  Prof          A             39              36  Female  137000   137.000
44  Prof          B             23              19  Female  151768   151.768
45  Prof          B             25              25  Female  140096   140.096
49  Prof          B             17              18  Female  122960   122.960
51  Prof          B             20              14  Female  127512   127.512
58  Prof          B             36              26  Female  144651   144.651
72  Prof          B             24              15  Female  161101   161.101
75  Prof          B             17              17  Female  124312   124.312

In [66]:
# Let's see what we get for our df_filter data frame
# Method .loc subsets the data frame based on the index values:
# loc = location
df_filter.loc[10:20,['rank','gender','salary']]

    rank gender  salary
10  Prof   Male  128250
11  Prof   Male  134778
13  Prof   Male  162200
14  Prof   Male  153750
15  Prof   Male  150480
19  Prof   Male  150500

In [67]:
# Unlike method .loc, method iloc selects rows (and columns) by absolute position:
# iloc = integer location
df_filter.iloc[10:20, [0,3,4,5]]

    rank  yearsOfService  gender  salary
26  Prof              19    Male  148750
27  Prof              43    Male  155865
29  Prof              20    Male  123683
31  Prof              21    Male  155750
35  Prof              23    Male  126933
36  Prof              45    Male  146856
39  Prof              18  Female  129000
40  Prof              36  Female  137000
44  Prof              19  Female  151768
45  Prof              25  Female  140096

In [68]:
# Restore the original order using the sort_index method
df_new.sort_index(axis=0, ascending = True, inplace = True)
df_new.head()

   rank discipline  yearsAfterPhD  yearsOfService gender  salary  salary_k
0  Prof          B             56              49   Male  186960   186.960
1  Prof          A             12               6   Male   93000    93.000
2  Prof          A             23              20   Male  110515   110.515
3  Prof          A             40              31   Male  131205   131.205
4  Prof          B             20              18   Male  104800   104.800

In [69]:
# Sort the data frame using 2 or more columns:
df_sorted2 = df_new.sort_values(by = ['yearsOfService', 'salary'], ascending = [True,False])
df_sorted2.head(15)

,rank,discipline,yearsAfterPhD,yearsOfService,gender,salary,salary_k
52,Prof,A,12,0,Female,105000,105.000
17,AsstProf,B,4,0,Male,92000,92.000
12,AsstProf,B,1,0,Male,88000,88.000
23,AsstProf,A,2,0,Male,85000,85.000
43,AsstProf,B,5,0,Female,77000,77.000
55,AsstProf,A,2,0,Female,72500,72.500
57,AsstProf,A,3,1,Female,72500,72.500
28,AsstProf,B,7,2,Male,91300,91.300
42,AsstProf,B,4,2,Female,80225,80.225
68,AsstProf,A,4,2,Female,77500,77.500
22,AsstProf,A,4,2,Male,73000,73.000
15,Prof,B,17,3,Male,150480,150.480
60,AsstProf,B,3,3,Female,92000,92.000
38,AsstProf,B,4,3,Male,91000,91.000
70,AsstProf,A,8,3,Female,78500,78.500

### Missing Values
To discuss how to handle missing values we will import the flights data set.

In [70]:
# Read a dataset with missing values
flights = pd.read_csv("http://rcs.bu.edu/examples/python/DataAnalysis/flights.csv")
flights.head()

,year,month,day,dep_time,dep_delay,arr_time,arr_delay,carrier,tailnum,flight,origin,dest,air_time,distance,hour,minute
0,2013,1,1,517.0,2.0,830.0,11.0,UA,N14228,1545,EWR,IAH,227.0,1400,5.0,17.0
1,2013,1,1,533.0,4.0,850.0,20.0,UA,N24211,1714,LGA,IAH,227.0,1416,5.0,33.0
2,2013,1,1,542.0,2.0,923.0,33.0,AA,N619AA,1141,JFK,MIA,160.0,1089,5.0,42.0
3,2013,1,1,554.0,-6.0,812.0,-25.0,DL,N668DN,461,LGA,ATL,116.0,762,5.0,54.0
4,2013,1,1,554.0,-4.0,740.0,12.0,UA,N39463,1696,EWR,ORD,150.0,719,5.0,54.0

In [71]:
flights.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 160754 entries, 0 to 160753
Data columns (total 16 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   year       160754 non-null  int64
 1   month      160754 non-null  int64
 2   day        160754 non-null  int64
 3   dep_time   158418 non-null  float64
 4   dep_delay  158418 non-null  float64
 5   arr_time   158275 non-null  float64
 6   arr_delay  157927 non-null  float64
 7   carrier    160754 non-null  object
 8   tailnum    159321 non-null  object
 9   flight     160754 non-null  int64
 10  origin     160754 non-null  object
 11  dest       160754 non-null  object
 12  air_time   157927 non-null  float64
 13  distance   160754 non-null  int64
 14  hour       158418 non-null  float64
 15  minute     158418 non-null  float64
dtypes: float64(7), int64(5), object(4)
memory usage: 19.6+ MB

In [72]:
# Select the rows that have at least one missing value
flights[flights.isnull().any(axis=1)].head()

,year,month,day,dep_time,dep_delay,arr_time,arr_delay,carrier,tailnum,flight,origin,dest,air_time,distance,hour,minute
330,2013,1,1,1807.0,29.0,2251.0,NaN,UA,N31412,1228,EWR,SAN,NaN,2425,18.0,7.0
403,2013,1,1,NaN,NaN,NaN,NaN,AA,N3EHAA,791,LGA,DFW,NaN,1389,NaN,NaN
404,2013,1,1,NaN,NaN,NaN,NaN,AA,N3EVAA,1925,LGA,MIA,NaN,1096,NaN,NaN
855,2013,1,2,2145.0,16.0,NaN,NaN,UA,N12221,1299,EWR,RSW,NaN,1068,21.0,45.0
858,2013,1,2,NaN,NaN,NaN,NaN,AA,NaN,133,JFK,LAX,NaN,2475,NaN,NaN

In [73]:
# Filter all the rows where arr_delay value is missing:
flights1 = flights[flights['arr_delay'].notnull( )]
flights1.head()

,year,month,day,dep_time,dep_delay,arr_time,arr_delay,carrier,tailnum,flight,origin,dest,air_time,distance,hour,minute
0,2013,1,1,517.0,2.0,830.0,11.0,UA,N14228,1545,EWR,IAH,227.0,1400,5.0,17.0
1,2013,1,1,533.0,4.0,850.0,20.0,UA,N24211,1714,LGA,IAH,227.0,1416,5.0,33.0
2,2013,1,1,542.0,2.0,923.0,33.0,AA,N619AA,1141,JFK,MIA,160.0,1089,5.0,42.0
3,2013,1,1,554.0,-6.0,812.0,-25.0,DL,N668DN,461,LGA,ATL,116.0,762,5.0,54.0
4,2013,1,1,554.0,-4.0,740.0,12.0,UA,N39463,1696,EWR,ORD,150.0,719,5.0,54.0

In [74]:
# Remove all the observations with missing values
flights2 = flights.dropna()

In [75]:
# Fill missing values with zeros
nomiss =flights['dep_delay'].fillna(0)
nomiss.isnull().any()

False

### Common Aggregation Functions:

The following functions are commonly used functions to aggregate data.

|Function|Description
|-------|--------
|min   | minimum
|max   | maximum
|count   | number of non-null observations
|sum   | sum of values
|mean  | arithmetic mean of values
|median | median
|mad | mean absolute deviation
|mode | mode
|prod   | product of values
|std  | standard deviation
|var | unbiased variance

In [76]:
# Find the number of non-missing values in each column
flights.describe()

,year,month,day,dep_time,dep_delay,arr_time,arr_delay,flight,air_time,distance,hour,minute
count,160754.0,160754.000000,160754.000000,158418.000000,158418.000000,158275.000000,157927.000000,160754.000000,157927.000000,160754.000000,158418.000000,158418.000000
mean,2013.0,6.547395,15.716567,1316.146006,9.463773,1517.471161,2.094537,1156.344987,180.685158,1282.445420,12.837582,32.387847
std,0.0,3.410001,8.762794,470.823715,36.545109,510.695413,41.479349,695.884283,97.507866,765.895383,4.725552,18.687423
min,2013.0,1.000000,1.000000,1.000000,-33.000000,1.000000,-75.000000,1.000000,21.000000,17.000000,0.000000,0.000000
25%,2013.0,4.000000,8.000000,855.000000,-5.000000,1112.000000,-19.000000,504.000000,111.000000,733.000000,8.000000,16.000000
50%,2013.0,7.000000,16.000000,1345.000000,-2.000000,1541.000000,-7.000000,1157.000000,153.000000,1076.000000,13.000000,32.000000
75%,2013.0,10.000000,23.000000,1725.000000,7.000000,1944.000000,9.000000,1715.000000,258.000000,1728.000000,17.000000,51.000000
max,2013.0,12.000000,31.000000,2400.000000,1014.000000,2400.000000,1007.000000,2599.000000,695.000000,4963.000000,24.000000,59.000000

In [77]:
flights.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 160754 entries, 0 to 160753
Data columns (total 16 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   year       160754 non-null  int64
 1   month      160754 non-null  int64
 2   day        160754 non-null  int64
 3   dep_time   158418 non-null  float64
 4   dep_delay  158418 non-null  float64
 5   arr_time   158275 non-null  float64
 6   arr_delay  157927 non-null  float64
 7   carrier    160754 non-null  object
 8   tailnum    159321 non-null  object
 9   flight     160754 non-null  int64
 10  origin     160754 non-null  object
 11  dest       160754 non-null  object
 12  air_time   157927 non-null  float64
 13  distance   160754 non-null  int64
 14  hour       158418 non-null  float64
 15  minute     158418 non-null  float64
dtypes: float64(7), int64(5), object(4)
memory usage: 19.6+ MB

In [78]:
# Find mean value for all the columns in the dataset
flights.min()

C:\Users\YSD\anaconda3\envs\SRIR\lib\site-packages\ipykernel_launcher.py:2: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.

year         2013
month           1
day             1
dep_time      1.0
dep_delay   -33.0
arr_time      1.0
arr_delay   -75.0
carrier        AA
flight          1
origin        EWR
dest          ANC
air_time     21.0
distance       17
hour          0.0
minute        0.0
dtype: object

In [79]:
# Let's compute summary statistic per a group':
flights.groupby('carrier')['dep_delay'].mean()

carrier
AA     8.586016
AS     5.804775
DL     9.264505
UA    12.106073
US     3.782418
Name: dep_delay, dtype: float64

In [80]:
# We can use agg() methods for aggregation:
flights[['dep_delay','arr_delay']].agg(['min','mean','max'])

        dep_delay    arr_delay
min    -33.000000   -75.000000
mean     9.463773     2.094537
max   1014.000000  1007.000000

In [81]:
# An example of computing different statistics for different columns
flights.agg({'dep_delay':['min','mean',max], 'carrier':['nunique']})

           dep_delay  carrier
min       -33.000000      NaN
mean        9.463773      NaN
max      1014.000000      NaN
nunique          NaN      5.0